services:
  spark-master:
    build: dockerfiles/spark
    command: master
    container_name: spark-master
    hostname: spark-master
    environment:
      SPARK_PUBLIC_DNS: spark-master
    networks:
      - spark
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./data/spark-master:/tmp/data
      - ./migrator/target/scala-2.13:/jars
      - ./parquet-data:/parquet-data
      - ./:/app

  spark-worker:
    build: dockerfiles/spark
    command: worker
    hostname: spark-worker
    container_name: spark-worker-1
    environment:
      SPARK_WORKER_CORES: 3
      SPARK_WORKER_MEMORY: 1024m
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: spark-worker
    networks:
      - spark
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./data/spark-worker:/tmp/data
      - ./parquet-data:/parquet-data
    depends_on:
      - spark-master

networks:
  spark:
