services:

  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:2.5.2"
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal

  spark-master:
    build: dockerfiles/spark
    command: master
    environment:
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 4040:4040
      - 8080:8080
    volumes:
      - ./spark-data:/app

  spark-worker:
    build: dockerfiles/spark
    command: worker
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4G
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081
    depends_on:
      - spark-master

  scylla:
    image: scylladb/scylla:6.0.1
    expose:
      - 8001
    ports:
      - "8001:8001"
    command: "--smp 1 --memory 2048M --alternator-port 8001 --alternator-write-isolation only_rmw_uses_lwt"
