name: Tests
on:
  push:
    branches:
      - master
      - actions-test
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Set up services
        run: docker compose -f docker-compose-tests.yml up -d
      - name: Build migrator
        run: ./build.sh
      - name: Run tests
        run: sbt test
      - name: Stop services
        run: docker compose -f docker-compose-tests.yml down
