name: Tests
on:
  push:
    branches:
      - master      
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-compose-tests.yml') }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Build migrator
        run: ./build.sh
      - name: Set up services
        run: |
          docker compose -f docker-compose-tests.yml up -d
          .github/wait-for-port.sh 9042 # ScyllaDB
          .github/wait-for-port.sh 8000 # ScyllaDB Alternator
          .github/wait-for-port.sh 8001 # DynamoDB
          .github/wait-for-port.sh 9043 # Cassandra
          .github/wait-for-port.sh 8080 # Spark master
          .github/wait-for-port.sh 8081 # Spark worker
      - name: Run tests
        run: sbt test
      - name: Stop services
        run: docker compose -f docker-compose-tests.yml down
